- hosts: winhost
  gather_facts: no
  tasks:
  - name: Copy the bundle.zip
    win_copy:
      src: GoogleChromeEnterpriseBundle64.zip
      dest: C:\\Temp\\

  - name: Extract the bundle
    win_unzip:
      src: c:\\Temp\\GoogleChromeEnterpriseBundle64.zip
      dest: C:\\Temp\\Chrome

  - name: Install Chrome
    win_package:
      path: C:\\Temp\\Chrome\\Installers\\GoogleChromeStandaloneEnterprise64.msi
      product_id: '{PRODUCT_IT}'
      wait: yes
      state: present
    when: ACTION == "Install"
